In [1]:
import numpy as np

In [2]:
#python code to create 1d array
a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [3]:
#python code to create 2d array
b=np.array([[1,2,3],[4,5,6]])
print(a)

[1 2 3 4 5]


In [4]:
#use of ndim property of numpy array
print(a.ndim)

1


In [6]:
print(b.ndim)

2


In [7]:
#using itemsize ..used to calculate the bit of one element of array
print(a.itemsize)

8


In [8]:
#using dtype property ....datatype of element stored in array 
print(a.dtype)

int64


In [9]:
#using size property...used to find the no of element in the array 
print(a.size)

5


In [11]:
#using shape property ....used to find the no of row and column in the array 
print(b.shape)

(2, 3)


In [13]:
#using reshape function .....change row to column and column to row 
print(b.reshape(3,2))

[[1 2]
 [3 4]
 [5 6]]


In [14]:
#using arange function ...used to create array of function in given range 
#range(5)-->0,1,2,3,4
#range(1,5)-->1,2,3,4
#range(1,5,2)-->1,3
a1=np.arange(5)
a2=np.arange(1,5)
a3=np.arange(1,5,2)
print(a1)
print(a2)
print(a3)


[0 1 2 3 4]
[1 2 3 4]
[1 3]


In [15]:
# use of arange function to create 2d array 
b1=np.arange(1,11).reshape(2,5)
print(b1)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [20]:
#use of ones()...this function ise use to create matrix of one(bydefault data type is float)
# b2=np.ones((2,4))
# b3=b2.astype(np.int32)
# print(b3)or
b2=np.ones((2,4)).astype(np.int32)
print(b2)

[[1 1 1 1]
 [1 1 1 1]]


In [21]:
#use of zeros.... used to generate matrix of 0(bedefault datatype is float)
b3=np.zeros((3,3)).astype(np.int32)
print(b3)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [22]:
# use of identity()....used to create an identity matrix
b4=np.identity(3).astype(np.int32)
print(b4)

[[1 0 0]
 [0 1 0]
 [0 0 1]]
